#:schema https://api.nuon.co/v1/general/config-schema?type=secret
name          = "tailscale_oauth_client_secret"
display_name  = "Tailscale OAuth Client Secret"
description   = "Client Secret for the Tailscale OAuth credentials."

kubernetes_sync             = true
kubernetes_secret_namespace = "tailscale"
kubernetes_secret_name      = "tailscale-oauth-client-secret"
