#:schema https://api.nuon.co/v1/general/config-schema?type=secret
name          = "tailscale_oauth_client_id"
display_name  = "Tailscale OAuth Client ID"
description   = "Client ID for the Tailscale OAuth credentials."

kubernetes_sync             = true
kubernetes_secret_namespace = "tailscale"
kubernetes_secret_name      = "tailscale-oauth-client-id"
