#:schema https://api.nuon.co/v1/general/config-schema?type=docker_build
name       = "api_image"
type       = "docker_build"
dockerfile = "Dockerfile"

[public_repo]
repo      = "nuonco/uptime-monitor"
directory = "api"
branch    = "main"
