#:schema https://api.nuon.co/v1/general/config-schema?type=container_image
name   = "img_tailscale_operator"
type   = "container_image"

[public]
image_url = "tailscale/k8s-operator"
tag       = "v1.90.6"
