#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes_manifests
name      = "headlamp_rbac"
type      = "kubernetes_manifest"
namespace = "headlamp"

manifest = "./3-headlamp-rbac/manifest.yaml"
