#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes_manifests
name      = "tailscale_proxy"
type      = "kubernetes_manifest"
namespace = "tailscale"

dependencies = ["tailscale_operator"]

manifest = "./3-tailscale-proxy/manifest.yaml"
