#:schema https://api.nuon.co/v1/general/config-schema?type=kubernetes_manifests
name      = "application_load_balancer"
type      = "kubernetes_manifest"
namespace = "uptime-monitor"

dependencies = ["ui", "headlamp"]

manifest = "./4-alb/manifest.yaml"
